(defproject clhorus "0.0.1-SNAPSHOT"
            :description "Clhorus experimentation project"
            :dependencies [[clj-time "0.9.0"]
                           [compojure "1.3.3"]
                           [com.novemberain/langohr "3.4.1"]
                           [com.stuartsierra/component "0.2.3"]
                           [danlentz/clj-uuid "0.1.2-SNAPSHOT"]
                           [http-kit "2.1.18"]
                           [korma "0.4.2"]
                           [mysql/mysql-connector-java "5.1.34"]
                           [org.clojure/clojure "1.7.0"]
                           [org.clojure/core.async "0.1.346.0-17112a-alpha"]
                           [org.clojure/java.jdbc "0.4.2"]
                           [org.clojure/data.json "0.2.6"]
                           [org.clojure/tools.nrepl "0.2.11"]
                           [ring/ring-defaults "0.1.2"]]
  :plugins [[lein-ring "0.8.13"]]
            :profiles {:dev {:source-paths ["dev"]
                             :dependencies [[javax.servlet/servlet-api "2.5"]
                                            [lein-midje "3.1.3"]
                                            [midje "1.6.3"]
                                            [org.clojure/tools.namespace "0.2.10"]
                                            [org.clojure/java.classpath "0.2.2"]
                                            [ring-mock "0.1.5"]]
                             :plugins      [[lein-midje "3.1.3"]]}}
  :aot [clhorus.core]
  :main clhorus.core)
